# Generated by Django 3.0.7 on 2022-05-07 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('NatID', models.CharField(max_length=200, null=True, verbose_name='National ID')),
                ('drugs', models.CharField(blank=True, choices=[('ampicillin iv', 'ampicillin iv'), (' gentamicin iv ', ' gentamicin iv '), ('chloramphenicol iv ', 'chloramphenicol iv '), ('ceftriaxone iv', 'ceftriaxone iv'), ('ciprofloxacin po', 'ciprofloxacin po'), ('metronidazole po', 'metronidazole po'), ('chloramphenicol iv', 'chloramphenicol iv'), ('tetracycline eye oint. 1%', 'tetracycline eye oint. 1%'), ('benzylpenicillin im/iv', 'benzylpenicillin im/iv'), ('Other(Specify)', 'Other(Specify)')], max_length=100, null=True, verbose_name='Drugs')),
                ('dosage', models.CharField(max_length=200, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=200, verbose_name='Frequency')),
                ('duration', models.CharField(max_length=200, verbose_name='Duration')),
                ('diagnosis', models.CharField(max_length=200)),
                ('comment', models.TextField(null=True, verbose_name='Add a comment on ICD10')),
                ('examination', models.TextField(null=True, verbose_name='Examination')),
                ('plan', models.TextField(null=True, verbose_name='Plan')),
                ('prescription', models.TextField(null=True, verbose_name='Prescription')),
                ('referrance', models.CharField(max_length=200, null=True, verbose_name='Referrance')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=200, null=True, verbose_name='Status Of Payment')),
                ('paymentType', models.CharField(choices=[('C', 'Consulting')], default='Consulting', max_length=1, verbose_name='Type Of payment')),
                ('paymentMethod', models.CharField(max_length=200, null=True, verbose_name='Method Of Payment')),
                ('medaid', models.CharField(default='None', max_length=200, null=True)),
                ('ecoNumber', models.CharField(default='None', max_length=200, null=True, verbose_name='Ecocash number')),
                ('total', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_payments', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)),
                ('Allergic', models.CharField(max_length=200)),
                ('Bp', models.CharField(max_length=200)),
                ('Pulse', models.CharField(max_length=200)),
                ('Temp', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
                ('SP02', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
