# Generated by Django 3.0.7 on 2022-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_description', models.CharField(blank=True, max_length=100)),
                ('group_code', models.CharField(blank=True, max_length=100)),
                ('group_description', models.CharField(blank=True, max_length=100)),
                ('icd10_3_code', models.CharField(blank=True, max_length=100)),
                ('icd10_3_code_description', models.CharField(blank=True, max_length=500)),
                ('icd10_code', models.CharField(blank=True, max_length=100)),
                ('who_full_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
