# Generated by Django 3.0.7 on 2022-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.IntegerField(blank=True)),
                ('medaid_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
